### ISSUE TITLE
请问可以修改时间吗，20s太快了，在哪里修改呢

### ISSUE THREAD

**Issue by bet-liujie** [DRSalieri/English-Helper#3]

**Comment by DRSalieri** [comment]
嗯嗯，我正在做，下个版本就会有了

**Comment by Michael1015198808** [comment]
您好， 1ac5925154dfb4d4c05ef0b9a622927e8362f988 之后就可以自由配置时间啦，设置完权限后使用`/背单词 set [选项] [值]`即可
![image](https://user-images.githubusercontent.com/32944191/131605195-2363c14c-3fc7-4b96-8e92-6a1c55db5560.png)

**Comment by Michael1015198808** [comment]
新版本的 release 预计今天就会放出来
