### ISSUE TITLE
疑似输入开始之后报错

### ISSUE THREAD

**Issue by lpc-eol** [DRSalieri/English-Helper#4]
![image](https://user-images.githubusercontent.com/76684848/128846348-f5a39d24-b03f-4077-8b30-e61e4b507bd9.png)

**Comment by lpc-eol** [comment]
输入开始     之后就看到后台报这个了

**Comment by lpc-eol** [comment]
又正常运行了..

**Comment by DRSalieri** [comment]
请问你是手动编译的吗，我在release版本里的是可以正常运行的。现在的代码里在一次merge后有一些小bug，我紧急修改一下

**Comment by Michael1015198808** [comment]
> 输入开始 之后就看到后台报这个了

bug是我引入的……非常抱歉，我在重构代码的时候不知道哪里引入了神秘bug :cry:

**Comment by Michael1015198808** [comment]
#6 应该把这个问题解决了，您再尝试一下

**Comment by lpc-eol** [comment]
正常运行了，谢谢

**Comment by Michael1015198808** [comment]
记得关一下issue。。。
